import { SampleAlert } from "../types";

export const SAMPLE_ALERTS: SampleAlert[] = [
  {
    id: "sms-genuine-1",
    name: "Genuine Bank SMS Alert",
    type: "SMS_GENUINE",
    bank: "Zenith Bank",
    description: "A standard automated transaction notification. Note the structured formatting, security-conscious account masking, and accurate ledger balancing.",
    content: `ZenithBank Credit
Amt: NGN 250,000.00
Acct: 232******789
Desc: FT:ZAINAB/TRF/MOBILE
Date: 20-Jul-2026 15:30:22
Bal: NGN 482,150.75`
  },
  {
    id: "sms-fake-1",
    name: "Counterfeit SMS Alert (Bulk SMS Forgery)",
    type: "SMS_FAKE",
    bank: "Zenith Bank (Spoofed)",
    description: "Typically sent via unauthorized bulk SMS gateways. Contains grammatical errors, lacks transaction time/seconds, and has static balance numbering.",
    content: `CREDIT ALERT !!!
Your Acct: 232******789 has been Credited with NGN 250,000.00
From: ZAINAB via Mobile Transfer.
Date: 20-Jul-2026 at 3:30PM.
Available Balance is NGN 482,150.75.
Thank you for banking with Zenith Bank.`
  },
  {
    id: "sms-genuine-2",
    name: "Genuine Mobile App Alert",
    type: "SMS_GENUINE",
    bank: "GTBank",
    description: "Genuine transaction alert with standard banking abbreviations, chronological timestamps, and authentic ledger detail formats.",
    content: `Txn: Credit
Acct: 011******542
Amt: NGN 75,000.00
Des: IPS/OPay/Zainab/Ref:9992384
Date: 20-Jul-2026 11:15:02
Bal: NGN 91,420.30`
  },
  {
    id: "sms-fake-2",
    name: "Counterfeit SMS Alert (Lacks Bank Headers)",
    type: "SMS_FAKE",
    bank: "GTBank (Spoofed)",
    description: "Scammer alert using basic messaging formats, missing the official transactional system ID and displaying irregular spacing.",
    content: `GTB Alert: You have received a transfer of NGN 75,000.00 from ZAINAB.
Ref: GTB-TRF-00129482.
Your new balance is NGN 91,420.30.
Check your app immediately.`
  },
  {
    id: "receipt-genuine-1",
    name: "Genuine Transaction Receipt",
    type: "RECEIPT_GENUINE",
    bank: "OPay",
    description: "An authentic transaction receipt with sharp, uniform brand fonts, a standard 30-character digital reference number, and a secure brand watermark.",
    imageUrl: "https://images.unsplash.com/photo-1554224155-8d04cb21cd6c?auto=format&fit=crop&w=600&q=80",
    estimatedAmount: "NGN 45,000.00",
    estimatedDate: "20-Jul-2026 10:20 AM"
  },
  {
    id: "receipt-fake-1",
    name: "Counterfeit Receipt (Font & Align Mismatches)",
    type: "RECEIPT_FAKE",
    bank: "OPay (Forged)",
    description: "A common forged receipt generated by basic graphic software. Features misaligned transaction amounts, a pixelated logo, and font-family inconsistency.",
    imageUrl: "https://images.unsplash.com/photo-1554224154-16000c2a8c3d?auto=format&fit=crop&w=600&q=80",
    estimatedAmount: "NGN 450,000.00",
    estimatedDate: "20-Jul-2026 10:24 AM"
  }
];

export const BANK_PROFILES = [
  {
    name: "OPay",
    color: "#00B970",
    refFormat: "260720xxxxxxxxxxxxxxxxxxxxxxxxx", // 30 digit starting with date YYMMDD
    smsSender: "OPay"
  },
  {
    name: "GTBank",
    color: "#DD4B39",
    refFormat: "011/TRF/260720/94823",
    smsSender: "GTBank"
  },
  {
    name: "Zenith Bank",
    color: "#E21A22",
    refFormat: "FT26072091823901",
    smsSender: "ZenithBank"
  },
  {
    name: "Palmpay",
    color: "#6F2DBD",
    refFormat: "PP2607201829384",
    smsSender: "PalmPay"
  },
  {
    name: "Access Bank",
    color: "#E45E20",
    refFormat: "AC26072049283412",
    smsSender: "AccessBank"
  }
];
